name: Testing
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Working Directory
        run: pwd

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build


