name: Testing
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependencies Install
        run: "bundle install"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run serve
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://127.0.0.1:4000/PLANLib/'


